version: 2.1
orbs:
  slack: circleci/slack@4.6.2
jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            apk add -U --no-cache curl jq
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - slack/notify:
          event: fail
          channel: C030C9JFXPS
          mentions: '@Dwayne'
          template: basic_fail_1
      - slack/notify:
          event: pass
          channel: C030C9JFXPS
          template: success_tagged_deploy_1
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply:
          context:
            - Terraform
      - slack/on-hold:
          context:
            - Terraform
          requires:
            - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
            - slack/on-hold
      - apply:
          context:
            - Terraform
          requires:
            - hold-apply
      - plan-destroy:
          context:
            - Terraform
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          context:
            - Terraform
          requires:
            - hold-destroy
